"""
Noise Robustness Evaluation Module for Equivariant Quantum Neural Networks (EqNN).

This script systematically evaluates the performance of pre-trained Quantum Neural Networks 
under varying levels of quantum inference noise. It leverages Hydra for configuration 
management and supports distributed multi-run executions. Results are isolated into 
unique CSV files per job to prevent I/O race conditions during parallel processing.
"""

import os
import csv
import random
import torch
import numpy as np
import logging
from tqdm import tqdm

import hydra
from omegaconf import DictConfig

# Custom module imports
from qnn import create_qnn
from train import execute_batch
from data_loading import (
    load_mnist_data, load_eurosat_data, 
    load_kaggle_nwpu_data, load_aug_mnist_data, add_sat_data,
    get_multiple_mnist_test_loaders
)

# Configure module-level logger
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

def set_seed(seed_val: int) -> None:
    """
    Sets the global random seeds to ensure deterministic behavior and reproducibility.
    
    Args:
        seed_val (int): The integer seed value for random number generators.
    """
    random.seed(seed_val)
    np.random.seed(seed_val)
    torch.manual_seed(seed_val)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed_val)

def parse_config_from_folder(folder_name: str) -> dict:
    """
    Extracts hyperparameter configurations encoded within the Hydra sweep directory names.
    
    Args:
        folder_name (str): The name of the directory generated by Hydra's multirun.
        
    Returns:
        dict: A dictionary mapping hyperparameter string keys to their corresponding values.
    """
    config = {}
    parts = folder_name.split(',')
    for part in parts:
        if '=' in part:
            key, value = part.split('=')
            config[key] = value
    return config

def get_multiple_dataloaders_wrapper(
    dataset_name: str, 
    N: int, 
    batch_size: int, 
    seeds: list[int], 
    augment_test: bool = False
):
    """
    Retrieves multiple test dataloaders for robust evaluation across different random splits.
    
    Args:
        dataset_name (str): The target dataset identifier (e.g., 'mnist').
        N (int): Number of data samples allocated.
        batch_size (int): Batch size used for the evaluation forward pass.
        seeds (list[int]): List of seed values to generate diverse test sets.
        augment_test (bool, optional): Applies data augmentation if True. Defaults to False.
        
    Returns:
        list: A list of PyTorch DataLoader objects.
        
    Raises:
        NotImplementedError: If the specified dataset is not supported by the loader mechanism.
    """
    if dataset_name == "mnist":
        return get_multiple_mnist_test_loaders(
            batch_size=batch_size, 
            N=N, 
            num_workers=0, 
            seeds=seeds, 
            augment_test=augment_test
        )
    else:
        raise NotImplementedError(f"Multiple test loaders not yet implemented for dataset: {dataset_name}.")

def evaluate_model_with_noise(
    model_path: str, 
    test_loader, 
    dev_str: str, 
    non_equivariance: int, 
    reps: int, 
    p_err: float,
    progress_desc: str = "Evaluating Batches",
    pbar_position: int = 0
) -> float:
    """
    Evaluates a trained Quantum Neural Network subjected to simulated quantum hardware noise.
    
    This function loads pre-trained model weights, constructs a fresh QNN architecture 
    incorporating the target inference error probability (`p_err`), and computes 
    the final classification accuracy over the provided test set.
    
    Args:
        model_path (str): Filepath to the saved model checkpoint (PyTorch .pt file).
        test_loader (DataLoader): PyTorch DataLoader containing the evaluation dataset.
        dev_str (str): Target computational device (e.g., 'cpu' or 'cuda').
        non_equivariance (int): Topological parameter governing symmetry breaking in the QNN.
        reps (int): Number of repeated circuit layers (ansatz depth).
        p_err (float): Target quantum error probability (e.g., depolarizing/bit-flip rate).
        progress_desc (str, optional): Custom string for the progress bar description.
        pbar_position (int, optional): Console line position for the tqdm progress bar.
        
    Returns:
        float: The normalized classification accuracy [0.0, 1.0] of the model.
    """
    dev = torch.device(dev_str)
    
    # 1. Load optimized parameters from the saved checkpoint
    checkpoint = torch.load(model_path, map_location=dev)
    params = checkpoint['params'].to(dev)
    phi = checkpoint['phi'].to(dev)
    
    # 2. Instantiate a noise-aware QNN environment for inference
    qnn = create_qnn(
        device="default.mixed", 
        non_equivariance=non_equivariance, 
        p_err=p_err, 
        reps=reps
    )
    
    # 3. Execute evaluation loop
    total_correct = 0
    total_samples = 0
    dataset_size = len(test_loader.dataset)
    
    with torch.no_grad():
        with tqdm(total=dataset_size, desc=progress_desc, leave=False, position=pbar_position) as pbar:
            for batch_images, batch_labels in test_loader:
                batch_labels = batch_labels.to(dev)
                
                # Perform forward pass through the noisy quantum circuit
                batch_predictions = execute_batch(qnn, batch_images, dev, params, phi)
                
                # Binarize output predictions (threshold at 0.5) and compute matches
                preds_binary = (batch_predictions.squeeze() > 0.5).long()
                total_correct += (preds_binary == batch_labels).sum().item()
                
                # Update progress tracking
                batch_len = batch_labels.size(0)
                total_samples += batch_len
                pbar.update(batch_len)

    # Return accuracy, adding a small epsilon to prevent zero-division errors
    return total_correct / (total_samples + 1e-8)


@hydra.main(version_base=None, config_path="config", config_name="config")
def main(cfg: DictConfig) -> None:
    """
    Main execution pipeline for evaluating noise robustness across trained models.
    Handles dynamic configurations via Hydra, isolating outputs to support parallel runs.
    """
    results_dir = "/data/giuseppedambruoso/eqnn/results/mnist"
    
    # Extract operational parameters dynamically from Hydra's configuration
    single_p_err = float(cfg.QNN.p_err)
    single_test_seed = int(cfg.DATA.seed)

    # Establish output directory structure
    output_dir = "noise_robustness_mnist"
    os.makedirs(output_dir, exist_ok=True)

    # Generate a uniquely identifiable CSV path to avoid race conditions during multithreaded runs
    output_csv = os.path.join(output_dir, f"noise_robustness_mnist_seed{single_test_seed}_perr{single_p_err}.csv")
    
    logger.info(f"Initiating evaluation job: Target p_err = {single_p_err}, Seed = {single_test_seed}")
    
    test_seeds = [single_test_seed]
    device_str = "cpu"
    
    # Initialize the results file with standardized headers
    with open(output_csv, "w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow([
            "dataset", "N", "train_seed", "non_equivariance", "reps", "train_epochs",
            "test_seed", "test_p_err", "augment_test", "test_accuracy"
        ])
    
    # Traverse the results directory to locate valid model checkpoints
    eval_paths = []
    for root, dirs, files in os.walk(results_dir):
        root_base = os.path.basename(root)
        # Apply filtering criteria to isolate the specific pre-trained models of interest
        if "final_model.pt" in files and "DATA.N=320" in root_base and "p_err=0," in root_base and "DATA.dataset=mnist" in root_base and "QNN.reps=2" in root_base and "GENERAL.seed=2" in root_base:
            eval_paths.append(root)

    # Iterate through all discovered models that match the criteria
    for folder_path in eval_paths:
        model_path = os.path.join(folder_path, "final_model.pt")
        folder_name = os.path.basename(folder_path)

        # Reconstruct the architectural configuration from the directory nomenclature
        config_folder = parse_config_from_folder(folder_name)
        dataset = config_folder.get("DATA.dataset", "mnist")
        N = int(config_folder.get("DATA.N", 20))
        train_seed = int(config_folder.get("GENERAL.seed", 2))
        non_eq = int(config_folder.get("QNN.non_equivariance", 3))
        reps = int(config_folder.get("QNN.reps", 1))
        epochs = int(config_folder.get("TRAINING.epochs", 60))
        batch_size = 1

        # Map integer parameters to human-readable descriptors for logging
        if non_eq == 4:
            model_name_str = "Equiv"
        elif non_eq == 3:
            model_name_str = "NonEquiv"
        else:
            model_name_str = f"Unknown_{non_eq}"

        # Initialize data loaders for both standard and augmented evaluation tracks
        try:
            test_loaders_orig = get_multiple_dataloaders_wrapper(dataset, N, batch_size, test_seeds, augment_test=False)
            test_loaders_aug = get_multiple_dataloaders_wrapper(dataset, N, batch_size, test_seeds, augment_test=True)
        except Exception as e:
            logger.error(f"Failed to load datasets for configuration {folder_name}. Error: {e}")
            continue

        # Evaluate against the specified seed split
        for test_seed, loader_orig, loader_aug in zip(test_seeds, test_loaders_orig, test_loaders_aug):
            
            # --- 1. Evaluate on Original (Unaugmented) Set ---
            set_seed(test_seed)
            acc_orig = evaluate_model_with_noise(
                model_path=model_path,
                test_loader=loader_orig,
                dev_str=device_str,
                non_equivariance=non_eq,
                reps=reps,
                p_err=single_p_err,
                progress_desc=f"{model_name_str} | p_err: {single_p_err} | seed: {test_seed} (Original Data)",
                pbar_position=0
            )

            # Persist original accuracy results
            with open(output_csv, "a", newline="") as f:
                writer = csv.writer(f)
                writer.writerow([dataset, N, train_seed, non_eq, reps, epochs, test_seed, single_p_err, False, acc_orig])

            # --- 2. Evaluate on Augmented Set ---
            set_seed(test_seed)
            acc_aug = evaluate_model_with_noise(
                model_path=model_path,
                test_loader=loader_aug,
                dev_str=device_str,
                non_equivariance=non_eq,
                reps=reps,
                p_err=single_p_err,
                progress_desc=f"{model_name_str} | p_err: {single_p_err} | seed: {test_seed} (Augmented Data)",
                pbar_position=0
            )

            # Persist augmented accuracy results
            with open(output_csv, "a", newline="") as f:
                writer = csv.writer(f)
                writer.writerow([dataset, N, train_seed, non_eq, reps, epochs, test_seed, single_p_err, True, acc_aug])

    logger.info(f"Evaluation process concluded. Data serialized successfully to {output_csv}")

if __name__ == "__main__":
    main()
