hydra:
  job_logging:
    root:
      level: INFO
  sweep:
    subdir: ${hydra.job.override_dirname}

GENERAL:
  seed: 1234
  dev: "cpu"
  verbose: True
  initialization_analysis: False

DATA:
  N: 20  # number of images in the training set
  dataset: "mnist"
  augment_test: True

QNN:
  device: "lightning.gpu"
  p_err: 0
  reps: 2
  equivariance: True
  twirling: False
  remove_cross_edge: True

TRAINING:
  epochs: 80
  learning_rate: 0.05
