# config/config.yaml
hydra:
  job_logging:
    root:
      level: INFO
  sweep:
    subdir: ${hydra.job.override_dirname}

GENERAL:
  seed: 1234
  dev: "cpu"
  verbose: True
  initialization_analysis: False

DATA:
  N: 20  # number of images in the training set
  dataset: "mnsit"
  augment_test: True

QNN:
  device: "lightning.qubit"
  non_equivariance: 0
  p_err: 0.01
  reps: 2

TRAINING:
  epochs: 80
  learning_rate: 0.05
